Upgrade typescript to ^2.8.0
This should hopefully fix error in travis build step `npm run check-ts`

Error: node_modules/@types/recompose/index.d.ts(23,47): error TS2304:
Cannot find name 'Exclude'.
Example build:
https://travis-ci.org/GriddleGriddle/Griddle/builds/441174637

Reason: The Exclude keyword used in @types/recompose was added in
Typescript 2.8
(https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#predefined-conditional-types).